disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - force_try
 - line_length
 - force_cast
 - nesting
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
